#!/bin/bash
WALLPAPER_DIR="$HOME/Wallpapers"

chosen=$(ls "$WALLPAPER_DIR" | rofi -dmenu -p "🖼 Wallpaper" -i)

if [ -n "$chosen" ]; then
    pkill swaybg
    swaybg -i "$WALLPAPER_DIR/$chosen" -m fill &
fi
